<?php
// $Id$

/**
 * Main module file for the MADPub module.
 *
 * This module is the core module for MADPub integration.  It provides
 * some basic API level functions and configurations.
 */

/**
 * Implementation of hook_help().
 */
function madpub_help($section) {
  switch ($section) {
    case 'admin/config/madpub':
      return '<p>'. t('Basic configuration for the MADPub integration.') .'</p>';
      
    case 'madpub':
      return '<p>'. t('Fill out the following form to send your Damage Assessment to ??.') .'</p>';
  }
}

/**
 * Implements hook_permission().
 */
function hook_permission() {
  return array(
    'administer madpub' => array(
      'title' => t('Administer MADPub'), 
      'description' => t('Administer configurations for MADPub.'),
    ),
    'input madpub' => array(
      'title' => t('Input MADPub'), 
      'description' => t('Fill out the MADPub form.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function madpub_menu() {
  $items['admin/config/madpub'] = array(
    'title' => 'MADPub',
    'description' => 'Basic configuration for MADPub integration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('madpub_admin_settings'),
    'access arguments' => array('administer madpub'),
  );
  $items['madpub'] = array(
    'title' => 'Damage Assessment Form',
    'description' => 'Fill out the following form to send your Damage Assessment to ??',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('madpub_form'),
    'access arguments' => array('input madpub'),
  );
  return $items;
}

/**
 * Admin settings form
 */
function madpub_admin_settings($form, &$form_state) {
  $form = array();
  
  $form['madpub_server_address'] = array(
    '#type' => 'textfield',
    '#title' => t('Server Address'),
    '#description' => t('This is the base REST address for push and pulling data from the MADPub server.'),
    '#default_value' => variable_get('madpub_server_address', ''),
  );
  
  return system_settings_form($form);
}

/**
 * Admin settings form
 */
function madpub_form($form, &$form_state) {

  $form['fieldset_contact_information'][''] = array(
    '#type' => '',
    '#title' => t(''),
    '#default_value' => !empty($form_state['values']['']) ? $form_state['values'][''] : '',
  );

  $form = array();
  
  // Contact Information
  $form['fieldset_contact_information'] = array(
    '#type' => 'fieldset',
    '#title' => t('Contact Information'),
    '#description' => t('Basic contact information.'),
  );
  $form['fieldset_contact_information']['first_name'] = array(
    '#type' => 'textfield',
    '#title' => t('First name'),
    '#default_value' => !empty($form_state['values']['first_name']) ? $form_state['values']['first_name'] : '',
  );
  $form['fieldset_contact_information']['last_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Last name'),
    '#default_value' => !empty($form_state['values']['last_name']) ? $form_state['values']['last_name'] : '',
  );
  $form['fieldset_contact_information']['pref_contact'] = array(
    '#type' => 'select',
    '#title' => t('Preferred method of contact'),
    '#options' => array(
      'mail' => t('Mail'),
      'phone' => t('Phone'),
      'e-mail' => t('EMail'),
    ),
    '#default_value' => !empty($form_state['values']['pref_contact']) ? $form_state['values']['pref_contact'] : '',
  );
  $form['fieldset_contact_information']['street_address_1'] = array(
    '#type' => 'textfield',
    '#title' => t('Street address'),
    '#default_value' => !empty($form_state['values']['street_address_1']) ? $form_state['values']['street_address_1'] : '',
  );
  $form['fieldset_contact_information']['city'] = array(
    '#type' => 'textfield',
    '#title' => t('City'),
    '#default_value' => !empty($form_state['values']['city']) ? $form_state['values']['city'] : '',
  );
  $form['fieldset_contact_information']['county'] = array(
    '#type' => 'textfield',
    '#title' => t('County'),
    '#default_value' => !empty($form_state['values']['county']) ? $form_state['values']['county'] : '',
  );
  $form['fieldset_contact_information']['state'] = array(
    '#type' => 'textfield',
    '#title' => t('State'),
    '#default_value' => !empty($form_state['values']['state']) ? $form_state['values']['state'] : '',
  );
  $form['fieldset_contact_information']['zip_code'] = array(
    '#type' => 'textfield',
    '#title' => t('Zip'),
    '#default_value' => !empty($form_state['values']['zip_code']) ? $form_state['values']['zip_code'] : '',
  );
  
  return $form;
} 
