<?php
// $Id$

/**
 * Main module file for the MADPub module.
 *
 * This module is the core module for MADPub integration.  It provides
 * some basic API level functions and configurations.
 */

/**
 * Implementation of hook_help().
 */
function madpub_help($section) {
  switch ($section) {
    case 'admin/config/madpub':
      return '<p>'. t('Basic configuration for the MADPub integration.') .'</p>';
      
    case 'madpub':
      return '<p>'. t('Fill out the following form to send your Damage Assessment to ??.  This is just a draft and does not actually work.') .'</p>';
  }
}

/**
 * Implements hook_permission().
 */
function hook_permission() {
  return array(
    'administer madpub' => array(
      'title' => t('Administer MADPub'), 
      'description' => t('Administer configurations for MADPub.'),
    ),
    'input madpub' => array(
      'title' => t('Input MADPub'), 
      'description' => t('Fill out the MADPub form.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function madpub_menu() {
  $items['admin/config/madpub'] = array(
    'title' => 'MADPub',
    'description' => 'Basic configuration for MADPub integration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('madpub_admin_settings'),
    'access arguments' => array('administer madpub'),
  );
  $items['madpub'] = array(
    'title' => 'Damage Assessment Form',
    'description' => 'Fill out the following form to send your Damage Assessment to ??',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('madpub_form'),
    'access arguments' => array('input madpub'),
  );
  return $items;
}

/**
 * Admin settings form
 */
function madpub_admin_settings($form, &$form_state) {
  $form = array();
  
  $form['madpub_server_address'] = array(
    '#type' => 'textfield',
    '#title' => t('Server Address'),
    '#description' => t('This is the base REST address for push and pulling data from the MADPub server.'),
    '#default_value' => variable_get('madpub_server_address', ''),
  );
  
  return system_settings_form($form);
}

/**
 * Input MADPub form
 */
function madpub_form($form, &$form_state) {

  $form['fieldset_contact_information'][''] = array(
    '#type' => '',
    '#title' => t(''),
    '#default_value' => !empty($form_state['values']['']) ? $form_state['values'][''] : '',
  );

  $form = array();
  
  // Contact Information
  $form['fieldset_contact_information'] = array(
    '#type' => 'fieldset',
    '#title' => t('Contact Information'),
    '#description' => t('Basic contact information.'),
  );
  $form['fieldset_contact_information']['first_name'] = array(
    '#type' => 'textfield',
    '#title' => t('First name'),
    '#default_value' => !empty($form_state['values']['first_name']) ? $form_state['values']['first_name'] : '',
  );
  $form['fieldset_contact_information']['last_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Last name'),
    '#default_value' => !empty($form_state['values']['last_name']) ? $form_state['values']['last_name'] : '',
  );
  $form['fieldset_contact_information']['pref_contact'] = array(
    '#type' => 'select',
    '#title' => t('Preferred method of contact'),
    '#options' => array(
      'mail' => t('Mail'),
      'phone' => t('Phone'),
      'e-mail' => t('EMail'),
    ),
    '#default_value' => !empty($form_state['values']['pref_contact']) ? $form_state['values']['pref_contact'] : 'e-mail',
  );
  $form['fieldset_contact_information']['street_address_1'] = array(
    '#type' => 'textfield',
    '#title' => t('Street address'),
    '#default_value' => !empty($form_state['values']['street_address_1']) ? $form_state['values']['street_address_1'] : '',
  );
  $form['fieldset_contact_information']['city'] = array(
    '#type' => 'textfield',
    '#title' => t('City'),
    '#default_value' => !empty($form_state['values']['city']) ? $form_state['values']['city'] : '',
  );
  $form['fieldset_contact_information']['county'] = array(
    '#type' => 'textfield',
    '#title' => t('County'),
    '#default_value' => !empty($form_state['values']['county']) ? $form_state['values']['county'] : '',
  );
  $form['fieldset_contact_information']['state'] = array(
    '#type' => 'textfield',
    '#title' => t('State'),
    '#default_value' => !empty($form_state['values']['state']) ? $form_state['values']['state'] : '',
  );
  $form['fieldset_contact_information']['zip_code'] = array(
    '#type' => 'textfield',
    '#title' => t('Zip'),
    '#default_value' => !empty($form_state['values']['zip_code']) ? $form_state['values']['zip_code'] : '',
  );
  
  // Damage
  $form['fieldset_damage'] = array(
    '#type' => 'fieldset',
    '#title' => t('Damage Information'),
    '#description' => t('Basic information on damage.'),
  );
  $form['fieldset_damage']['dam_date'] = array(
    '#type' => 'textfield',
    '#title' => t('Date of damage'),
    '#default_value' => !empty($form_state['values']['dam_date']) ? $form_state['values']['dam_date'] : '',
  );
  $form['fieldset_damage']['loc_date'] = array(
    '#type' => 'textfield',
    '#title' => t('Location of damage'),
    '#default_value' => !empty($form_state['values']['loc_date']) ? $form_state['values']['loc_date'] : '',
  );
  
  // FEMA
  $form['fieldset_fema'] = array(
    '#type' => 'fieldset',
    '#title' => t('FEMA Information'),
    '#description' => t('Information specific for FEMA.'),
  );
  $form['fieldset_fema']['FEMA_app'] = array(
    '#type' => 'select',
    '#title' => t('Started an application with FEMA?'),
    '#options' => array(
      'yes' => t('Yes'),
      'no' => t('No'),
    ),
    '#default_value' => !empty($form_state['values']['FEMA_app']) ? $form_state['values']['FEMA_app'] : '',
  );
  $form['fieldset_fema']['FEMA_ref'] = array(
    '#type' => 'textfield',
    '#title' => t('Reference number'),
    '#default_value' => !empty($form_state['values']['FEMA_ref']) ? $form_state['values']['FEMA_ref'] : '',
  );
  
  // Submit
  $form['submit_madpub'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
  
  return $form;
}

/**
 * Validation function for MADPub form.
 */
function madpub_form_validate($form, &$form_state) {

}

/**
 * Submit function for MADPub form.
 */
function madpub_form_submit($form, &$form_state) {
  $base_url = variable_get('madpub_server_address', '');
  $data = array();
  
  // Get rid of data we don't want
  foreach ($form_state['values'] as $id => $value) {
    if (!in_array($id, array('submit_madpub', 'form_build_id', 'form_token', 'form_id', 'op'))) {
      $data[$id] = $value;
    }
  }
  
  // Prepare request
  $data = http_build_query($data, '', '&');
  $headers = array();
  $options = array(
    'headers' => array(
      'Accept' => 'application/json',
    ),
    'method' => 'POST',
    'data' => $data
  );

  // Make request
  $response = drupal_http_request($base_url . '??', $options);
  
  if ($response->code == 200) {
    drupal_set_message('Message sent.');
  }
  else {
    drupal_set_message('Message not sent.');
  }
}
